### PR TITLE
Add Feishin Remote Support

### PR DESCRIPTION
**Pull request by AshleyDeo**
Added support for Feishin Remote Control Server. 
Feishin is desktop client to play music from jellyfin or navidrome server. Remote control server allows other devices to control the desktop app.
Tested with rainmeter and obs from edge and chrome.
**Working**
* Song info, pause/play, prev/next song, duration, volume, like/rating
* Cover art (only works when cover art image is enabled)

**Not working**
* Song progress - not passed through server

### CODE REVIEW

**Comment by AshleyDeo** [comment]
I updated the selectors

**Comment by keifufu** [comment]
This looks better, you can also make use of `navigator.mediaSession` for artwork and title, artist, etc. since feishin seems to implement it

**Comment by keifufu** [comment]
You use the desktop version? How does that work with this extension?

**Comment by AshleyDeo** [comment]
i just have the remote server running in a tab. i use monstercat rainmeter plugin

**Pull request closed without merging**
